"""Shared export utilities — build rich JSON + Markdown from DialogueState."""
from __future__ import annotations
import json
from datetime import datetime
from pathlib import Path

from core.state import DialogueState


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _n(v) -> str:
    if isinstance(v, int):
        return f"{v:,}"
    if isinstance(v, float):
        return str(v)
    return str(v) if v is not None else "—"


# ---------------------------------------------------------------------------
# Build the API-response-style export dict from live state
# ---------------------------------------------------------------------------

def build_export_dict(
    state: DialogueState,
    config_dict: dict | None = None,
    override_log: list | None = None,
) -> dict:
    """Build a JSON-serialisable export dict that matches the /debates/{id} API shape."""
    cfg = config_dict or {}

    acts_out = [
        {
            "act_id":        a.act_id,
            "session_id":    a.session_id,
            "turn":          a.turn,
            "agent":         a.agent,
            "agent_role":    a.agent_role,
            "act_type":      a.act_type,
            "claim_id":      a.claim_id,
            "target_act_id": a.target_act_id,
            "content":       a.content,     # full, untruncated
            "reason":        a.reason,
            "input_tokens":  a.input_tokens,
            "output_tokens": a.output_tokens,
            "model_used":    a.model_used,
            "timestamp":     a.timestamp,
        }
        for a in state.acts
    ]

    claims_out = [
        {
            "claim_id":    c.claim_id,
            "session_id":  c.session_id,
            "author":      c.author,
            "content":     c.content,
            "status":      c.status,
            "last_updated": c.last_updated,
        }
        for c in state.claims.values()
    ]

    status = "closed" if (state.phase == "closed" or state.closure_reason) else "running"

    return {
        "session_id":    state.session_id,
        "created_at":    state.created_at,
        "closed_at":     state.closed_at,
        "status":        status,
        "debate_title":  state.debate_title,
        "topic":         state.topic,
        "closure_reason": state.closure_reason,
        "config":        cfg,
        "acts":          acts_out,
        "claims":        claims_out,
        "override_log":  override_log or [],
    }


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------

def build_markdown(data: dict) -> str:
    """Render a debate export dict as a rich human-readable Markdown transcript."""
    cfg  = data.get("config") or {}
    acts = data.get("acts") or []

    created_at = data.get("created_at") or ""
    try:
        dt = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
        date_str = dt.strftime("%Y-%m-%d")
        time_str = dt.strftime("%H:%M:%S UTC")
    except Exception:
        date_str = created_at[:10] if len(created_at) >= 10 else created_at
        time_str = created_at[11:19] if len(created_at) >= 19 else ""

    # Derive nicknames from act records (more reliable than config for moderator)
    nickname_map: dict[str, str] = {}
    for act in acts:
        role  = act.get("agent_role", "")
        agent = act.get("agent", "")
        if role and agent and role not in nickname_map:
            nickname_map[role] = agent

    prop_nick  = cfg.get("proposition_nickname") or nickname_map.get("proposition", "Proposition")
    opp_nick   = cfg.get("opposition_nickname")  or nickname_map.get("opposition",  "Opposition")
    mod_nick   = nickname_map.get("moderator", "Moderator")
    synth_nick = nickname_map.get("synthesiser", "Synthesiser")

    tok: dict[str, list[int]] = {
        "proposition": [0, 0],
        "opposition":  [0, 0],
        "moderator":   [0, 0],
        "synthesiser": [0, 0],
    }
    for act in acts:
        role = act.get("agent_role", "")
        if role in tok:
            tok[role][0] += act.get("input_tokens")  or 0
            tok[role][1] += act.get("output_tokens") or 0
    total_in  = sum(v[0] for v in tok.values())
    total_out = sum(v[1] for v in tok.values())

    title    = data.get("debate_title") or data.get("topic") or data.get("session_id", "Debate")
    steelman = cfg.get("steelman_mode", False)

    lines: list[str] = [
        f"# {title}",
        "",
        "> Generated by [Agora](https://github.com/shehuphd/agora)",
        "",
        "## Metadata",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Session | `{data.get('session_id', '')}` |",
        f"| Date | {date_str} |",
        f"| Time | {time_str} |",
        f"| Topic | {data.get('topic', '')} |",
        f"| Status | {data.get('status', '')} |",
    ]
    if data.get("closure_reason"):
        lines.append(f"| Closure reason | {data['closure_reason']} |")

    lines += [
        "",
        "## Participants",
        "",
        "| Role | Nickname | Model | Temperature |",
        "|------|----------|-------|-------------|",
        f"| Proposition | {prop_nick} | {cfg.get('proposition_model', '—')} | {cfg.get('temperature_proposition', '—')} |",
        f"| Opposition  | {opp_nick}  | {cfg.get('opposition_model',  '—')} | {cfg.get('temperature_opposition',  '—')} |",
        f"| Moderator   | {mod_nick}  | {cfg.get('moderator_model',   '—')} | — |",
        "",
        "## Settings",
        "",
        "| Parameter | Value |",
        "|-----------|-------|",
        f"| Max turns | {_n(cfg.get('max_turns'))} |",
        f"| Max time | {_n(cfg.get('max_time_minutes'))} min |",
        f"| Token budget | {_n(cfg.get('token_budget'))} |",
        f"| Min challenges | {_n(cfg.get('min_challenges'))} |",
        f"| Min concessions | {_n(cfg.get('min_concessions'))} |",
        f"| Repetition tolerance | {_n(cfg.get('repetition_tolerance'))} |",
        f"| Aggression | {_n(cfg.get('aggression'))} |",
        f"| Rapoport (steelman) mode | {'Yes' if steelman else 'No'} |",
        "",
        "## Token Usage",
        "",
        "| Agent | Input | Output | Total |",
        "|-------|------:|-------:|------:|",
        f"| {prop_nick} | {_n(tok['proposition'][0])} | {_n(tok['proposition'][1])} | {_n(sum(tok['proposition']))} |",
        f"| {opp_nick}  | {_n(tok['opposition'][0])}  | {_n(tok['opposition'][1])}  | {_n(sum(tok['opposition']))}  |",
        f"| {mod_nick}  | {_n(tok['moderator'][0])}   | {_n(tok['moderator'][1])}   | {_n(sum(tok['moderator']))}   |",
    ]
    if tok["synthesiser"][0] or tok["synthesiser"][1]:
        lines.append(
            f"| {synth_nick} | {_n(tok['synthesiser'][0])} | {_n(tok['synthesiser'][1])} | {_n(sum(tok['synthesiser']))} |"
        )
    lines += [
        f"| **Total** | **{_n(total_in)}** | **{_n(total_out)}** | **{_n(total_in + total_out)}** |",
        "",
    ]

    override_log = data.get("override_log") or []
    if override_log:
        lines += [
            "## Mid-Run Overrides",
            "",
            "| Timestamp | Field | Old Value | New Value |",
            "|-----------|-------|----------:|----------:|",
        ]
        for ov in override_log:
            field   = ov.get("field", "")
            old_val = _n(ov.get("old_value")) if ov.get("old_value") is not None else "original"
            new_val = _n(ov.get("new_value", ""))
            ts      = str(ov.get("timestamp", ""))[:19].replace("T", " ")
            lines.append(f"| {ts} | {field} | {old_val} | {new_val} |")
        lines.append("")

    lines += [
        "## Transcript",
        "",
    ]

    for act in acts:
        act_type = act.get("act_type", "")
        agent    = act.get("agent") or act.get("agent_role", "")
        turn     = act.get("turn", "")
        content  = act.get("content", "")
        reason   = act.get("reason", "")
        claim_id = act.get("claim_id", "")
        model    = act.get("model_used", "")

        lines.append(f"### Turn {turn} · {agent} · {act_type}")
        lines.append("")
        meta_parts = []
        if claim_id:
            meta_parts.append(f"claim `{claim_id}`")
        if model:
            meta_parts.append(f"model: {model}")
        if meta_parts:
            lines.append(f"*{' · '.join(meta_parts)}*")
            lines.append("")
        if content:
            lines.append(content)
            lines.append("")
        if reason:
            lines.append(f"*{reason}*")
            lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Filesystem writers
# ---------------------------------------------------------------------------

def write_debate_files(state: DialogueState, run_dir: Path) -> None:
    """Rewrite debate.json and debate.md in run_dir from current state.

    Called after every checkpoint so the files are always current.
    Reads config.json and overrides.json from the run dir if they exist.
    """
    config_path   = run_dir / "config.json"
    overrides_path = run_dir / "overrides.json"

    config_dict: dict = {}
    if config_path.exists():
        try:
            config_dict = json.loads(config_path.read_text(encoding="utf-8"))
        except Exception:
            pass

    override_log: list = []
    if overrides_path.exists():
        try:
            override_log = json.loads(overrides_path.read_text(encoding="utf-8"))
        except Exception:
            pass

    data = build_export_dict(state, config_dict, override_log)

    (run_dir / "debate.json").write_text(json.dumps(data, indent=2), encoding="utf-8")
    (run_dir / "debate.md").write_text(build_markdown(data), encoding="utf-8")
